#!/bin/bash

link=`pbpaste`

if [ -z $link ]; then
  echo "Please copy a product url from https://www.amazon.co.uk to your clipboard"
  exit 1
fi

re="^https://www.amazon.co.uk/([a-z]+/(product/)?[A-Z0-9]+).*"

if [[ $link =~ $re ]]; then
  asin=${BASH_REMATCH[1]}
  affiliatelink="https://www.amazon.co.uk/${asin}?tag=thescounm0f-21"
  echo $affiliatelink | pbcopy
  echo "Scoundrel link: ${affiliatelink} copied to clipboard"
  exit 0
else
  echo "Could not extract ASIN from link $link"
  exit 2
fi
