#!/bin/bash
echo "Setting local git repo to Schibsted git credentials"
git config --local user.name "Dan Etherington"
git config --local user.email "dan.etherington@schibsted.com"
echo "Local credentials set to":
git config --local --get-regexp "^user"
