#!/bin/sh
echo "Setting local git repo to baseonmars git credentials"
git config --local user.name "baseonmars"
git config --local user.email "dan@baseonmars.co.uk"
echo "Local credentials set to":
git config --local --get-regexp "^user"
